# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

env:
  ## Sets environment variable
  GIT_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}  
  name: environment variables for dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git branch name
      run: echo ${{env.GIT_BRANCH_NAME}}
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: ACCESS KEYS FOR DEV
      if:  env.GIT_BRANCH_NAME == 'develop'
      uses: |
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build with test
      if:  env.GIT_BRANCH_NAME == 'test'
      run: |
        echo "${{env.GIT_BRANCH_NAME}}"
        mvn -B install --file pom.xml
        
    - name: Build with develop
      if:  env.GIT_BRANCH_NAME == 'develop'
      run: |
        echo "${{env.GIT_BRANCH_NAME}}"
        mvn version
